### ISSUE TITLE
IOS: after adding Voximplant, project wont compile

### ISSUE THREAD

**Issue by izaa** [voximplant/react-native-voximplant#65] opened 2019-02-03 09:08 UTC
Hi,

i get following error when adding this package to one boilerplate: https://github.com/thecodingmachine/react-native-boilerplate 

RN version 0.57.8 and react 16.6.3. Hot could I solve this? 

Actually, i have had many problems with Xcode and cocoapods but havent seen this kind of errors before :( Any help would be very very appreciated, thanks!

```
Undefined symbols for architecture x86_64:
  "google::LogMessage::LogMessage(char const*, int, int)", referenced from:
      facebook::react::CxxNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_1::operator()() const in CxxNativeModule.o
      facebook::react::JSException::buildMessage(OpaqueJSContext const*, OpaqueJSValue const*, OpaqueJSString*, char const*) in JSCHelpers.o
      facebook::react::NativeToJsBridge::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, folly::dynamic&&)::$_1::operator()(facebook::react::JSExecutor*) const in NativeToJsBridge.o
      facebook::react::NativeToJsBridge::invokeCallback(double, folly::dynamic&&)::$_2::operator()(facebook::react::JSExecutor*) const in NativeToJsBridge.o
  "double_conversion::DoubleToStringConverter::ToShortestIeeeNumber(double, doubl

.....


```

**My podfile:**

```

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Boilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'RCTImage',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTLinkingIOS',
    # Add any other subspecs you want to use in your project
  ]

  pod 'react-native-voximplant', path: '../node_modules/react-native-voximplant'
  
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'Boilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

**Comment by YuliaGrigorieva** [comment] 2019-02-04 18:14
Hello!

I have tried to build https://github.com/thecodingmachine/react-native-boilerplate with Voximplant React Native SDK and was not able to reproduce the issue (I built for simulator)

I have followed all instructions in boilerplate project + I did the following:
1. remove all `xcodeproj` files from Libraries group in Xcode (to avoid duplication of react libs)
2. disabled bitcode for Boilerplate project and all pods

I have found the same issue reported in here: https://github.com/facebook/react-native/issues/17893
However the fixes they propose in the comments are mostly related to other react-native + CocoaPods issues (valid for earlier RN version than 0.57.x)

Currently I could recommend only to do the extra steps that I have described and clean the project, including `pod deintegrate && pod install`.

If you provide a sample project (as zip) on which the issue is reproducible, I could try to investigate it further.

Best regards,
Yulia Grigorieva

**Comment by ruscoder** [comment] 2019-02-11 12:35
@izaa @YuliaGrigorieva  I had a similar problem. The problem is reproducible only when you use cocoapods 1.6.0 (the latest).  
After I downgraded cocapods to 1.5.3 - everything is OK.

**Comment by YuliaGrigorieva** [comment] 2019-04-05 15:46
The issue seems to be related to React/jsi target that misses DoubleConversation and glog dependencies for cocoa pods integration.

The issue should be fixed in the latest RN version.

Closing the issue for now, feel free to reopen it.

Best regards,
Yulia Grigorieva

**Closed by YuliaGrigorieva** 2019-04-05 15:46 UTC
