### ISSUE TITLE
'MISSING_PERMISSION' error while trying to call

### ISSUE THREAD

**Issue by skibrit** [voximplant/react-native-voximplant#111] opened 2020-04-15 01:22 UTC
I'm trying to initiate an outgoing call using voximplant but getting this error 

"'MISSING_PERMISSION'"

**Comment by YuliaGrigorieva** [comment] 2020-04-15 05:56
Hello @skibrit !

MISSING_PERMISSION error means that the microphone and/or camera permission is not granted by the user. These are runtime permissions that should be checked and asked on android.

Please take a look at the permission request example: https://github.com/voximplant/react-native-demo/blob/6e6bdabdb03ac9c00057aa65bfb1184c978b5294/src/screens/MainScreen.js#L86-L103

Best regards,
Yulia Grigorieva

**Comment by skibrit** [comment] 2020-04-15 14:49
Hi thanx 'MISSING_PERMISSION' error resolved.

But now I'm facing another issue  "Normal termination" "Forbidden" when trying to call to a PSTN number

I'm trying to develop an application where the user will be able to call from the app to PSTN and also will receive calls from PSTN to the app.

I've followed this example to test the feature. But facing the forbidden error.

`https://voximplant.com/blog/click-to-call-for-web-and-mobile-application`

**Comment by YuliaGrigorieva** [comment] 2020-04-16 08:04
Hello @skibrit ,

I suppose the issue is caused by incorrect callerId. 

CallerID of the calling user that will be displayed to the called user. Whitespaces are not allowed. A valid phone number that can be used to call back is required. Following phone numbers can be used:
A real phone number that is rented from Voximplant. IMPORTANT: test numbers can't be used.
Any phone number that is verified via an automated call from Voximplant and confirmation code

I close this issue for now as the original issue is resolved.

Best regards,
Yulia Grigorieva

**Closed by YuliaGrigorieva** 2020-04-16 08:04 UTC
