### ISSUE TITLE
Not compatible with RN 0.54.0 at least on ios

### ISSUE THREAD

**Issue by jameslporter** [voximplant/react-native-voximplant#44] opened 2018-09-21 16:29 UTC
I was able to setup the android side with no apparent problems. However when I setup the podfile as describe I ran into this build error.

/Users/jamesporter/apps/hoplon/node_modules/react-native/React/Base/RCTBridgeModule.h:10:9: 'React/RCTDefines.h' file not found

/Users/jamesporter/apps/hoplon/node_modules/react-native-voximplant/ios/VIAudioDeviceModule.m:5:9: In file included from /Users/jamesporter/apps/hoplon/node_modules/react-native-voximplant/ios/VIAudioDeviceModule.m:5:

/Users/jamesporter/apps/hoplon/node_modules/react-native-voximplant/ios/VIAudioDeviceModule.h:8:9: In file included from /Users/jamesporter/apps/hoplon/node_modules/react-native-voximplant/ios/VIAudioDeviceModule.h:8:

After some searching it appears that RCTBatchedBridge has gone away with RN 0.54.0 version.

https://github.com/facebook/react-native/releases/tag/v0.54.0

iOS specific removals
Delete RCTBatchedBridge (816d417 by @mhorowitz)

**Comment by jameslporter** [comment] 2018-09-25 17:31
So I updated my podfile using the demo as a reference and added the postinstall hack. Now I'm left with this error below.

/Users/jamesporter/apps/hoplon/node_modules/react-native/React/Base/RCTBridgeModule.h:10:9: 'React/RCTDefines.h' file not found
/Users/jamesporter/apps/hoplon/node_modules/react-native-voximplant/ios/VICameraModule.m:5:9: In file included from /Users/jamesporter/apps/hoplon/node_modules/react-native-voximplant/ios/VICameraModule.m:5:
/Users/jamesporter/apps/hoplon/node_modules/react-native-voximplant/ios/VICameraModule.h:8:9: In file included from /Users/jamesporter/apps/hoplon/node_modules/react-native-voximplant/ios/VICameraModule.h:8:

That's one error with the two following lines showing the path that code was included from.

The postinstall requirement should be fixed rather than using a sed hack(which doesn't work on all platforms). If you really don't want to fix it at least mention it in the quickstart guide. The quickstart should yield you a functional environment if you follow the steps on a new project every time.

**Comment by jameslporter** [comment] 2018-09-28 19:58
RN
App.js
https://gist.github.com/jameslporter/b7d4f8c3c38e57d23f6435fe148f5b6c

Podfile:
https://gist.github.com/jameslporter/f21789157d258f8617aa4fa321c09e92
Let me know what else you need.

**Comment by YuliaGrigorieva** [comment] 2018-10-02 12:08
Hello!

Thank you for the information provided!

The issue is caused by different requirements for react-native-maps and react-native-voximplant modules’ integration.
Voximplant React Native SDK for iOS is built atop of Voximplant iOS SDK that is provided as dynamic framework. 
To integrate Voximplant React Native SDK to iOS project you need to:
1. add `use_frameworks!` line in your Podfile
https://github.com/voximplant/react-native-demo/blob/e7fe552989fd7d52dae64f574ec19024be923be0/ios/Podfile#L6
2. use React from development pods (i.e. do not remove it from pods project) and remove references to all react `*.xcodeproj` in the `Libraries` section
3. disable bitcode

But react-native-maps has the dependency of Google-Maps-iOS-Utils that has iOS 7 support and can’t be used as Cocoa Touch framework. However they have provided some workaround that you can try: 
https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md
Google-Maps-iOS-Utils project has a pull request to support `use_frameworks!` in the Podfile, but it is not clear when it will be merged: https://github.com/googlemaps/google-maps-ios-utils/pull/183

Best regards,
Yulia Grigorieva

**Comment by YuliaGrigorieva** [comment] 2019-04-05 15:44
Hello!

Today we have released Voximplant React Native SDK 1.6.0. Starting this release `use_frameworks!` is no longer mandatory and the issue with integration to the project where google maps are used, should be resolved.

Closing this issue for now.

Best regards,
Yulia Grigorieva

**Closed by YuliaGrigorieva** 2019-04-05 15:44 UTC
